# Site settings
title: SAFE Network
email: frabrunelle@gmail.com
description: "The SAFE (Secure Access for Everyone) network can be best described as a fully distributed data management service."
baseurl: "/"
url: "http://www.safenetwork.io"
twitter_username: frabrunelle
github_username: frabrunelle
facebook_username: frabrunelle

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
