# Site settings
title: SAFE Network
email: frabrunelle@gmail.com
description: "The SAFE (Secure Access for Everyone) network can be best described as a fully distributed data management service."
baseurl: ""
url: "http://www.safenetwork.io"
paginate: 5
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
