# Site settings
title: safenetwork.io
email: frabrunelle@gmail.com
description: "The SAFE (Secure Access for Everyone) network can be best described as a fully distributed data management service."
baseurl: ""
url: "http://www.safenetwork.io"
twitter_username: safenetwork_io
github_username: safenetwork
facebook_username: pages/safenetworkio/388183547995712

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
